// Copy the redirect page + generated wailsjs bindings into dist/ — the
// embedded assets the window loads while the real deck boots on the UI port.
// Paths resolve against THIS file (the shell may run us from anywhere).
import { copyFileSync, cpSync, existsSync, mkdirSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const here = dirname(fileURLToPath(import.meta.url));
mkdirSync(join(here, "dist"), { recursive: true });
copyFileSync(join(here, "index.html"), join(here, "dist", "index.html"));
// wailsjs (runtime + go bindings) is generated by `wails build` into
// frontend/wailsjs — embed it so the redirect page can call App.UiPort().
if (existsSync(join(here, "wailsjs"))) {
  cpSync(join(here, "wailsjs"), join(here, "dist", "wailsjs"), { recursive: true });
}
console.log("frontend build ok");
